spring:
  application:
    name: spaceagency
  datasource:
    url: jdbc:mysql://localhost:3306/space-agency-directory
    username: springstudent
    password: springstudent
  messages:
    encoding: UTF-8

flyway:
  enabled: true
  baseline-on-migrate: true
  default-schema: space-agency-directory
  schemas: space-agency-directory