spring:
  application:
    name: spaceagency
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
  messages:
    encoding: UTF-8
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2ley7a57j6xbxrle.us.auth0.com/
          audiences:
            - "${AUTH0_AUDIENCE}"

flyway:
  enabled: true
  baseline-on-migrate: true
  default-schema: space-agency-directory
  schemas: space-agency-directory

management:
  endpoints:
    web:
      exposure:
        include: "health,info"